server.port=8089
spring.application.name=ms-clientes-mayoristas

# Conexión a MySQL Workbench
spring.datasource.url=jdbc:mysql://localhost:3306/db_carnistock_clientes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=duoc2026

# Configuración Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true